// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet_api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddressPasswordHashMessage struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressPasswordHashMessage) Reset()         { *m = AddressPasswordHashMessage{} }
func (m *AddressPasswordHashMessage) String() string { return proto.CompactTextString(m) }
func (*AddressPasswordHashMessage) ProtoMessage()    {}
func (*AddressPasswordHashMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bd94de71a6388e, []int{0}
}

func (m *AddressPasswordHashMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressPasswordHashMessage.Unmarshal(m, b)
}
func (m *AddressPasswordHashMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressPasswordHashMessage.Marshal(b, m, deterministic)
}
func (m *AddressPasswordHashMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressPasswordHashMessage.Merge(m, src)
}
func (m *AddressPasswordHashMessage) XXX_Size() int {
	return xxx_messageInfo_AddressPasswordHashMessage.Size(m)
}
func (m *AddressPasswordHashMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressPasswordHashMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AddressPasswordHashMessage proto.InternalMessageInfo

func (m *AddressPasswordHashMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddressPasswordHashMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddressPasswordHashMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type SignatureMessage struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignatureMessage) Reset()         { *m = SignatureMessage{} }
func (m *SignatureMessage) String() string { return proto.CompactTextString(m) }
func (*SignatureMessage) ProtoMessage()    {}
func (*SignatureMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bd94de71a6388e, []int{1}
}

func (m *SignatureMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignatureMessage.Unmarshal(m, b)
}
func (m *SignatureMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignatureMessage.Marshal(b, m, deterministic)
}
func (m *SignatureMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignatureMessage.Merge(m, src)
}
func (m *SignatureMessage) XXX_Size() int {
	return xxx_messageInfo_SignatureMessage.Size(m)
}
func (m *SignatureMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignatureMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignatureMessage proto.InternalMessageInfo

func (m *SignatureMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type PasswordMessage struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordMessage) Reset()         { *m = PasswordMessage{} }
func (m *PasswordMessage) String() string { return proto.CompactTextString(m) }
func (*PasswordMessage) ProtoMessage()    {}
func (*PasswordMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bd94de71a6388e, []int{2}
}

func (m *PasswordMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordMessage.Unmarshal(m, b)
}
func (m *PasswordMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordMessage.Marshal(b, m, deterministic)
}
func (m *PasswordMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordMessage.Merge(m, src)
}
func (m *PasswordMessage) XXX_Size() int {
	return xxx_messageInfo_PasswordMessage.Size(m)
}
func (m *PasswordMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordMessage proto.InternalMessageInfo

func (m *PasswordMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AddressMessage struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressMessage) Reset()         { *m = AddressMessage{} }
func (m *AddressMessage) String() string { return proto.CompactTextString(m) }
func (*AddressMessage) ProtoMessage()    {}
func (*AddressMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_34bd94de71a6388e, []int{3}
}

func (m *AddressMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressMessage.Unmarshal(m, b)
}
func (m *AddressMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressMessage.Marshal(b, m, deterministic)
}
func (m *AddressMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressMessage.Merge(m, src)
}
func (m *AddressMessage) XXX_Size() int {
	return xxx_messageInfo_AddressMessage.Size(m)
}
func (m *AddressMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AddressMessage proto.InternalMessageInfo

func (m *AddressMessage) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*AddressPasswordHashMessage)(nil), "api.AddressPasswordHashMessage")
	proto.RegisterType((*SignatureMessage)(nil), "api.SignatureMessage")
	proto.RegisterType((*PasswordMessage)(nil), "api.PasswordMessage")
	proto.RegisterType((*AddressMessage)(nil), "api.AddressMessage")
}

func init() { proto.RegisterFile("wallet_api.proto", fileDescriptor_34bd94de71a6388e) }

var fileDescriptor_34bd94de71a6388e = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4f, 0xcc, 0xc9,
	0x49, 0x2d, 0x89, 0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c,
	0xc8, 0x54, 0x4a, 0xe3, 0x92, 0x72, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x0e, 0x48, 0x2c, 0x2e,
	0x2e, 0xcf, 0x2f, 0x4a, 0xf1, 0x48, 0x2c, 0xce, 0xf0, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15,
	0x92, 0xe0, 0x62, 0x4f, 0x84, 0xc8, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42,
	0x52, 0x5c, 0x1c, 0x05, 0x50, 0x0d, 0x12, 0x4c, 0x60, 0x29, 0x38, 0x5f, 0x48, 0x88, 0x8b, 0x25,
	0x23, 0xb1, 0x38, 0x43, 0x82, 0x59, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x56, 0x32, 0xe0, 0x12,
	0x08, 0xce, 0x4c, 0xcf, 0x4b, 0x2c, 0x29, 0x2d, 0x4a, 0x85, 0x99, 0x2e, 0xc3, 0xc5, 0x59, 0x0c,
	0x13, 0x03, 0x9b, 0xcf, 0x13, 0x84, 0x10, 0x50, 0xd2, 0xe5, 0xe2, 0x87, 0x39, 0x09, 0xa6, 0x01,
	0xd9, 0x52, 0x46, 0x54, 0x4b, 0x95, 0xb4, 0xb8, 0xf8, 0xa0, 0x1e, 0x21, 0xe8, 0x78, 0xa3, 0x09,
	0x8c, 0x5c, 0x5c, 0x88, 0xe0, 0x10, 0xb2, 0xe6, 0xe2, 0x71, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d,
	0x07, 0x8b, 0x09, 0x89, 0xe8, 0x81, 0x02, 0x09, 0xcd, 0x72, 0x29, 0x61, 0xb0, 0x28, 0xaa, 0x1d,
	0x4a, 0x0c, 0x42, 0xae, 0x5c, 0x9c, 0x70, 0x8f, 0x09, 0xc9, 0x23, 0xab, 0xc1, 0x12, 0xa0, 0x52,
	0xa2, 0x60, 0x05, 0xe8, 0x21, 0xa1, 0xc4, 0x90, 0xc4, 0x06, 0x8e, 0x13, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8c, 0xa9, 0x45, 0x99, 0xa7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletApiClient is the client API for WalletApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletApiClient interface {
	CreateWallet(ctx context.Context, in *PasswordMessage, opts ...grpc.CallOption) (*AddressMessage, error)
	Signature(ctx context.Context, in *AddressPasswordHashMessage, opts ...grpc.CallOption) (*SignatureMessage, error)
}

type walletApiClient struct {
	cc *grpc.ClientConn
}

func NewWalletApiClient(cc *grpc.ClientConn) WalletApiClient {
	return &walletApiClient{cc}
}

func (c *walletApiClient) CreateWallet(ctx context.Context, in *PasswordMessage, opts ...grpc.CallOption) (*AddressMessage, error) {
	out := new(AddressMessage)
	err := c.cc.Invoke(ctx, "/api.wallet_api/CreateWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletApiClient) Signature(ctx context.Context, in *AddressPasswordHashMessage, opts ...grpc.CallOption) (*SignatureMessage, error) {
	out := new(SignatureMessage)
	err := c.cc.Invoke(ctx, "/api.wallet_api/Signature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletApiServer is the server API for WalletApi service.
type WalletApiServer interface {
	CreateWallet(context.Context, *PasswordMessage) (*AddressMessage, error)
	Signature(context.Context, *AddressPasswordHashMessage) (*SignatureMessage, error)
}

func RegisterWalletApiServer(s *grpc.Server, srv WalletApiServer) {
	s.RegisterService(&_WalletApi_serviceDesc, srv)
}

func _WalletApi_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletApiServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.wallet_api/CreateWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletApiServer).CreateWallet(ctx, req.(*PasswordMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletApi_Signature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressPasswordHashMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletApiServer).Signature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.wallet_api/Signature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletApiServer).Signature(ctx, req.(*AddressPasswordHashMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.wallet_api",
	HandlerType: (*WalletApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _WalletApi_CreateWallet_Handler,
		},
		{
			MethodName: "Signature",
			Handler:    _WalletApi_Signature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_api.proto",
}
