// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/Contract.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceCode int32

const (
	ResourceCode_BANDWIDTH ResourceCode = 0
	ResourceCode_ENERGY    ResourceCode = 1
)

var ResourceCode_name = map[int32]string{
	0: "BANDWIDTH",
	1: "ENERGY",
}

var ResourceCode_value = map[string]int32{
	"BANDWIDTH": 0,
	"ENERGY":    1,
}

func (x ResourceCode) String() string {
	return proto.EnumName(ResourceCode_name, int32(x))
}

func (ResourceCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{0}
}

type AccountCreateContract struct {
	OwnerAddress         []byte      `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	AccountAddress       []byte      `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Type                 AccountType `protobuf:"varint,3,opt,name=type,proto3,enum=protocol.AccountType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AccountCreateContract) Reset()         { *m = AccountCreateContract{} }
func (m *AccountCreateContract) String() string { return proto.CompactTextString(m) }
func (*AccountCreateContract) ProtoMessage()    {}
func (*AccountCreateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{0}
}

func (m *AccountCreateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCreateContract.Unmarshal(m, b)
}
func (m *AccountCreateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCreateContract.Marshal(b, m, deterministic)
}
func (m *AccountCreateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCreateContract.Merge(m, src)
}
func (m *AccountCreateContract) XXX_Size() int {
	return xxx_messageInfo_AccountCreateContract.Size(m)
}
func (m *AccountCreateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCreateContract.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCreateContract proto.InternalMessageInfo

func (m *AccountCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *AccountCreateContract) GetAccountAddress() []byte {
	if m != nil {
		return m.AccountAddress
	}
	return nil
}

func (m *AccountCreateContract) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_Normal
}

// Update account name. Account name is not unique now.
type AccountUpdateContract struct {
	AccountName          []byte   `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	OwnerAddress         []byte   `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountUpdateContract) Reset()         { *m = AccountUpdateContract{} }
func (m *AccountUpdateContract) String() string { return proto.CompactTextString(m) }
func (*AccountUpdateContract) ProtoMessage()    {}
func (*AccountUpdateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{1}
}

func (m *AccountUpdateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountUpdateContract.Unmarshal(m, b)
}
func (m *AccountUpdateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountUpdateContract.Marshal(b, m, deterministic)
}
func (m *AccountUpdateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountUpdateContract.Merge(m, src)
}
func (m *AccountUpdateContract) XXX_Size() int {
	return xxx_messageInfo_AccountUpdateContract.Size(m)
}
func (m *AccountUpdateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountUpdateContract.DiscardUnknown(m)
}

var xxx_messageInfo_AccountUpdateContract proto.InternalMessageInfo

func (m *AccountUpdateContract) GetAccountName() []byte {
	if m != nil {
		return m.AccountName
	}
	return nil
}

func (m *AccountUpdateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

// Set account id if the account has no id. Account id is unique and case insensitive.
type SetAccountIdContract struct {
	AccountId            []byte   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OwnerAddress         []byte   `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAccountIdContract) Reset()         { *m = SetAccountIdContract{} }
func (m *SetAccountIdContract) String() string { return proto.CompactTextString(m) }
func (*SetAccountIdContract) ProtoMessage()    {}
func (*SetAccountIdContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{2}
}

func (m *SetAccountIdContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAccountIdContract.Unmarshal(m, b)
}
func (m *SetAccountIdContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAccountIdContract.Marshal(b, m, deterministic)
}
func (m *SetAccountIdContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAccountIdContract.Merge(m, src)
}
func (m *SetAccountIdContract) XXX_Size() int {
	return xxx_messageInfo_SetAccountIdContract.Size(m)
}
func (m *SetAccountIdContract) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAccountIdContract.DiscardUnknown(m)
}

var xxx_messageInfo_SetAccountIdContract proto.InternalMessageInfo

func (m *SetAccountIdContract) GetAccountId() []byte {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *SetAccountIdContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

type TransferContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ToAddress            []byte   `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferContract) Reset()         { *m = TransferContract{} }
func (m *TransferContract) String() string { return proto.CompactTextString(m) }
func (*TransferContract) ProtoMessage()    {}
func (*TransferContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{3}
}

func (m *TransferContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferContract.Unmarshal(m, b)
}
func (m *TransferContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferContract.Marshal(b, m, deterministic)
}
func (m *TransferContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferContract.Merge(m, src)
}
func (m *TransferContract) XXX_Size() int {
	return xxx_messageInfo_TransferContract.Size(m)
}
func (m *TransferContract) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferContract.DiscardUnknown(m)
}

var xxx_messageInfo_TransferContract proto.InternalMessageInfo

func (m *TransferContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *TransferContract) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *TransferContract) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransferAssetContract struct {
	AssetName            []byte   `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	OwnerAddress         []byte   `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ToAddress            []byte   `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferAssetContract) Reset()         { *m = TransferAssetContract{} }
func (m *TransferAssetContract) String() string { return proto.CompactTextString(m) }
func (*TransferAssetContract) ProtoMessage()    {}
func (*TransferAssetContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{4}
}

func (m *TransferAssetContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferAssetContract.Unmarshal(m, b)
}
func (m *TransferAssetContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferAssetContract.Marshal(b, m, deterministic)
}
func (m *TransferAssetContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferAssetContract.Merge(m, src)
}
func (m *TransferAssetContract) XXX_Size() int {
	return xxx_messageInfo_TransferAssetContract.Size(m)
}
func (m *TransferAssetContract) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferAssetContract.DiscardUnknown(m)
}

var xxx_messageInfo_TransferAssetContract proto.InternalMessageInfo

func (m *TransferAssetContract) GetAssetName() []byte {
	if m != nil {
		return m.AssetName
	}
	return nil
}

func (m *TransferAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *TransferAssetContract) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *TransferAssetContract) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type VoteAssetContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	VoteAddress          [][]byte `protobuf:"bytes,2,rep,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"`
	Support              bool     `protobuf:"varint,3,opt,name=support,proto3" json:"support,omitempty"`
	Count                int32    `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteAssetContract) Reset()         { *m = VoteAssetContract{} }
func (m *VoteAssetContract) String() string { return proto.CompactTextString(m) }
func (*VoteAssetContract) ProtoMessage()    {}
func (*VoteAssetContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{5}
}

func (m *VoteAssetContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteAssetContract.Unmarshal(m, b)
}
func (m *VoteAssetContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteAssetContract.Marshal(b, m, deterministic)
}
func (m *VoteAssetContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteAssetContract.Merge(m, src)
}
func (m *VoteAssetContract) XXX_Size() int {
	return xxx_messageInfo_VoteAssetContract.Size(m)
}
func (m *VoteAssetContract) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteAssetContract.DiscardUnknown(m)
}

var xxx_messageInfo_VoteAssetContract proto.InternalMessageInfo

func (m *VoteAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *VoteAssetContract) GetVoteAddress() [][]byte {
	if m != nil {
		return m.VoteAddress
	}
	return nil
}

func (m *VoteAssetContract) GetSupport() bool {
	if m != nil {
		return m.Support
	}
	return false
}

func (m *VoteAssetContract) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type VoteWitnessContract struct {
	OwnerAddress         []byte                      `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Votes                []*VoteWitnessContract_Vote `protobuf:"bytes,2,rep,name=votes,proto3" json:"votes,omitempty"`
	Support              bool                        `protobuf:"varint,3,opt,name=support,proto3" json:"support,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *VoteWitnessContract) Reset()         { *m = VoteWitnessContract{} }
func (m *VoteWitnessContract) String() string { return proto.CompactTextString(m) }
func (*VoteWitnessContract) ProtoMessage()    {}
func (*VoteWitnessContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{6}
}

func (m *VoteWitnessContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteWitnessContract.Unmarshal(m, b)
}
func (m *VoteWitnessContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteWitnessContract.Marshal(b, m, deterministic)
}
func (m *VoteWitnessContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteWitnessContract.Merge(m, src)
}
func (m *VoteWitnessContract) XXX_Size() int {
	return xxx_messageInfo_VoteWitnessContract.Size(m)
}
func (m *VoteWitnessContract) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteWitnessContract.DiscardUnknown(m)
}

var xxx_messageInfo_VoteWitnessContract proto.InternalMessageInfo

func (m *VoteWitnessContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *VoteWitnessContract) GetVotes() []*VoteWitnessContract_Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *VoteWitnessContract) GetSupport() bool {
	if m != nil {
		return m.Support
	}
	return false
}

type VoteWitnessContract_Vote struct {
	VoteAddress          []byte   `protobuf:"bytes,1,opt,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"`
	VoteCount            int64    `protobuf:"varint,2,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteWitnessContract_Vote) Reset()         { *m = VoteWitnessContract_Vote{} }
func (m *VoteWitnessContract_Vote) String() string { return proto.CompactTextString(m) }
func (*VoteWitnessContract_Vote) ProtoMessage()    {}
func (*VoteWitnessContract_Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{6, 0}
}

func (m *VoteWitnessContract_Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteWitnessContract_Vote.Unmarshal(m, b)
}
func (m *VoteWitnessContract_Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteWitnessContract_Vote.Marshal(b, m, deterministic)
}
func (m *VoteWitnessContract_Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteWitnessContract_Vote.Merge(m, src)
}
func (m *VoteWitnessContract_Vote) XXX_Size() int {
	return xxx_messageInfo_VoteWitnessContract_Vote.Size(m)
}
func (m *VoteWitnessContract_Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteWitnessContract_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_VoteWitnessContract_Vote proto.InternalMessageInfo

func (m *VoteWitnessContract_Vote) GetVoteAddress() []byte {
	if m != nil {
		return m.VoteAddress
	}
	return nil
}

func (m *VoteWitnessContract_Vote) GetVoteCount() int64 {
	if m != nil {
		return m.VoteCount
	}
	return 0
}

type UpdateSettingContract struct {
	OwnerAddress               []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress            []byte   `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ConsumeUserResourcePercent int64    `protobuf:"varint,3,opt,name=consume_user_resource_percent,json=consumeUserResourcePercent,proto3" json:"consume_user_resource_percent,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *UpdateSettingContract) Reset()         { *m = UpdateSettingContract{} }
func (m *UpdateSettingContract) String() string { return proto.CompactTextString(m) }
func (*UpdateSettingContract) ProtoMessage()    {}
func (*UpdateSettingContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{7}
}

func (m *UpdateSettingContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSettingContract.Unmarshal(m, b)
}
func (m *UpdateSettingContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSettingContract.Marshal(b, m, deterministic)
}
func (m *UpdateSettingContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSettingContract.Merge(m, src)
}
func (m *UpdateSettingContract) XXX_Size() int {
	return xxx_messageInfo_UpdateSettingContract.Size(m)
}
func (m *UpdateSettingContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSettingContract.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSettingContract proto.InternalMessageInfo

func (m *UpdateSettingContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *UpdateSettingContract) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *UpdateSettingContract) GetConsumeUserResourcePercent() int64 {
	if m != nil {
		return m.ConsumeUserResourcePercent
	}
	return 0
}

type WitnessCreateContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Url                  []byte   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WitnessCreateContract) Reset()         { *m = WitnessCreateContract{} }
func (m *WitnessCreateContract) String() string { return proto.CompactTextString(m) }
func (*WitnessCreateContract) ProtoMessage()    {}
func (*WitnessCreateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{8}
}

func (m *WitnessCreateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WitnessCreateContract.Unmarshal(m, b)
}
func (m *WitnessCreateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WitnessCreateContract.Marshal(b, m, deterministic)
}
func (m *WitnessCreateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessCreateContract.Merge(m, src)
}
func (m *WitnessCreateContract) XXX_Size() int {
	return xxx_messageInfo_WitnessCreateContract.Size(m)
}
func (m *WitnessCreateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessCreateContract.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessCreateContract proto.InternalMessageInfo

func (m *WitnessCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *WitnessCreateContract) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

type WitnessUpdateContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	UpdateUrl            []byte   `protobuf:"bytes,12,opt,name=update_url,json=updateUrl,proto3" json:"update_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WitnessUpdateContract) Reset()         { *m = WitnessUpdateContract{} }
func (m *WitnessUpdateContract) String() string { return proto.CompactTextString(m) }
func (*WitnessUpdateContract) ProtoMessage()    {}
func (*WitnessUpdateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{9}
}

func (m *WitnessUpdateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WitnessUpdateContract.Unmarshal(m, b)
}
func (m *WitnessUpdateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WitnessUpdateContract.Marshal(b, m, deterministic)
}
func (m *WitnessUpdateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WitnessUpdateContract.Merge(m, src)
}
func (m *WitnessUpdateContract) XXX_Size() int {
	return xxx_messageInfo_WitnessUpdateContract.Size(m)
}
func (m *WitnessUpdateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_WitnessUpdateContract.DiscardUnknown(m)
}

var xxx_messageInfo_WitnessUpdateContract proto.InternalMessageInfo

func (m *WitnessUpdateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *WitnessUpdateContract) GetUpdateUrl() []byte {
	if m != nil {
		return m.UpdateUrl
	}
	return nil
}

type AssetIssueContract struct {
	OwnerAddress            []byte                             `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Name                    []byte                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Abbr                    []byte                             `protobuf:"bytes,3,opt,name=abbr,proto3" json:"abbr,omitempty"`
	TotalSupply             int64                              `protobuf:"varint,4,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	FrozenSupply            []*AssetIssueContract_FrozenSupply `protobuf:"bytes,5,rep,name=frozen_supply,json=frozenSupply,proto3" json:"frozen_supply,omitempty"`
	TrxNum                  int32                              `protobuf:"varint,6,opt,name=trx_num,json=trxNum,proto3" json:"trx_num,omitempty"`
	Num                     int32                              `protobuf:"varint,8,opt,name=num,proto3" json:"num,omitempty"`
	StartTime               int64                              `protobuf:"varint,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                 int64                              `protobuf:"varint,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Order                   int64                              `protobuf:"varint,11,opt,name=order,proto3" json:"order,omitempty"`
	VoteScore               int32                              `protobuf:"varint,16,opt,name=vote_score,json=voteScore,proto3" json:"vote_score,omitempty"`
	Description             []byte                             `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	Url                     []byte                             `protobuf:"bytes,21,opt,name=url,proto3" json:"url,omitempty"`
	FreeAssetNetLimit       int64                              `protobuf:"varint,22,opt,name=free_asset_net_limit,json=freeAssetNetLimit,proto3" json:"free_asset_net_limit,omitempty"`
	PublicFreeAssetNetLimit int64                              `protobuf:"varint,23,opt,name=public_free_asset_net_limit,json=publicFreeAssetNetLimit,proto3" json:"public_free_asset_net_limit,omitempty"`
	PublicFreeAssetNetUsage int64                              `protobuf:"varint,24,opt,name=public_free_asset_net_usage,json=publicFreeAssetNetUsage,proto3" json:"public_free_asset_net_usage,omitempty"`
	PublicLatestFreeNetTime int64                              `protobuf:"varint,25,opt,name=public_latest_free_net_time,json=publicLatestFreeNetTime,proto3" json:"public_latest_free_net_time,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                           `json:"-"`
	XXX_unrecognized        []byte                             `json:"-"`
	XXX_sizecache           int32                              `json:"-"`
}

func (m *AssetIssueContract) Reset()         { *m = AssetIssueContract{} }
func (m *AssetIssueContract) String() string { return proto.CompactTextString(m) }
func (*AssetIssueContract) ProtoMessage()    {}
func (*AssetIssueContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{10}
}

func (m *AssetIssueContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetIssueContract.Unmarshal(m, b)
}
func (m *AssetIssueContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetIssueContract.Marshal(b, m, deterministic)
}
func (m *AssetIssueContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetIssueContract.Merge(m, src)
}
func (m *AssetIssueContract) XXX_Size() int {
	return xxx_messageInfo_AssetIssueContract.Size(m)
}
func (m *AssetIssueContract) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetIssueContract.DiscardUnknown(m)
}

var xxx_messageInfo_AssetIssueContract proto.InternalMessageInfo

func (m *AssetIssueContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *AssetIssueContract) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AssetIssueContract) GetAbbr() []byte {
	if m != nil {
		return m.Abbr
	}
	return nil
}

func (m *AssetIssueContract) GetTotalSupply() int64 {
	if m != nil {
		return m.TotalSupply
	}
	return 0
}

func (m *AssetIssueContract) GetFrozenSupply() []*AssetIssueContract_FrozenSupply {
	if m != nil {
		return m.FrozenSupply
	}
	return nil
}

func (m *AssetIssueContract) GetTrxNum() int32 {
	if m != nil {
		return m.TrxNum
	}
	return 0
}

func (m *AssetIssueContract) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *AssetIssueContract) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *AssetIssueContract) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *AssetIssueContract) GetOrder() int64 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *AssetIssueContract) GetVoteScore() int32 {
	if m != nil {
		return m.VoteScore
	}
	return 0
}

func (m *AssetIssueContract) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *AssetIssueContract) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *AssetIssueContract) GetFreeAssetNetLimit() int64 {
	if m != nil {
		return m.FreeAssetNetLimit
	}
	return 0
}

func (m *AssetIssueContract) GetPublicFreeAssetNetLimit() int64 {
	if m != nil {
		return m.PublicFreeAssetNetLimit
	}
	return 0
}

func (m *AssetIssueContract) GetPublicFreeAssetNetUsage() int64 {
	if m != nil {
		return m.PublicFreeAssetNetUsage
	}
	return 0
}

func (m *AssetIssueContract) GetPublicLatestFreeNetTime() int64 {
	if m != nil {
		return m.PublicLatestFreeNetTime
	}
	return 0
}

type AssetIssueContract_FrozenSupply struct {
	FrozenAmount         int64    `protobuf:"varint,1,opt,name=frozen_amount,json=frozenAmount,proto3" json:"frozen_amount,omitempty"`
	FrozenDays           int64    `protobuf:"varint,2,opt,name=frozen_days,json=frozenDays,proto3" json:"frozen_days,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetIssueContract_FrozenSupply) Reset()         { *m = AssetIssueContract_FrozenSupply{} }
func (m *AssetIssueContract_FrozenSupply) String() string { return proto.CompactTextString(m) }
func (*AssetIssueContract_FrozenSupply) ProtoMessage()    {}
func (*AssetIssueContract_FrozenSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{10, 0}
}

func (m *AssetIssueContract_FrozenSupply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetIssueContract_FrozenSupply.Unmarshal(m, b)
}
func (m *AssetIssueContract_FrozenSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetIssueContract_FrozenSupply.Marshal(b, m, deterministic)
}
func (m *AssetIssueContract_FrozenSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetIssueContract_FrozenSupply.Merge(m, src)
}
func (m *AssetIssueContract_FrozenSupply) XXX_Size() int {
	return xxx_messageInfo_AssetIssueContract_FrozenSupply.Size(m)
}
func (m *AssetIssueContract_FrozenSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetIssueContract_FrozenSupply.DiscardUnknown(m)
}

var xxx_messageInfo_AssetIssueContract_FrozenSupply proto.InternalMessageInfo

func (m *AssetIssueContract_FrozenSupply) GetFrozenAmount() int64 {
	if m != nil {
		return m.FrozenAmount
	}
	return 0
}

func (m *AssetIssueContract_FrozenSupply) GetFrozenDays() int64 {
	if m != nil {
		return m.FrozenDays
	}
	return 0
}

type ParticipateAssetIssueContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ToAddress            []byte   `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	AssetName            []byte   `protobuf:"bytes,3,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	Amount               int64    `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParticipateAssetIssueContract) Reset()         { *m = ParticipateAssetIssueContract{} }
func (m *ParticipateAssetIssueContract) String() string { return proto.CompactTextString(m) }
func (*ParticipateAssetIssueContract) ProtoMessage()    {}
func (*ParticipateAssetIssueContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{11}
}

func (m *ParticipateAssetIssueContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParticipateAssetIssueContract.Unmarshal(m, b)
}
func (m *ParticipateAssetIssueContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParticipateAssetIssueContract.Marshal(b, m, deterministic)
}
func (m *ParticipateAssetIssueContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipateAssetIssueContract.Merge(m, src)
}
func (m *ParticipateAssetIssueContract) XXX_Size() int {
	return xxx_messageInfo_ParticipateAssetIssueContract.Size(m)
}
func (m *ParticipateAssetIssueContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipateAssetIssueContract.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipateAssetIssueContract proto.InternalMessageInfo

func (m *ParticipateAssetIssueContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ParticipateAssetIssueContract) GetToAddress() []byte {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *ParticipateAssetIssueContract) GetAssetName() []byte {
	if m != nil {
		return m.AssetName
	}
	return nil
}

func (m *ParticipateAssetIssueContract) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type FreezeBalanceContract struct {
	OwnerAddress         []byte       `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	FrozenBalance        int64        `protobuf:"varint,2,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`
	FrozenDuration       int64        `protobuf:"varint,3,opt,name=frozen_duration,json=frozenDuration,proto3" json:"frozen_duration,omitempty"`
	Resource             ResourceCode `protobuf:"varint,10,opt,name=resource,proto3,enum=protocol.ResourceCode" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FreezeBalanceContract) Reset()         { *m = FreezeBalanceContract{} }
func (m *FreezeBalanceContract) String() string { return proto.CompactTextString(m) }
func (*FreezeBalanceContract) ProtoMessage()    {}
func (*FreezeBalanceContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{12}
}

func (m *FreezeBalanceContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreezeBalanceContract.Unmarshal(m, b)
}
func (m *FreezeBalanceContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreezeBalanceContract.Marshal(b, m, deterministic)
}
func (m *FreezeBalanceContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreezeBalanceContract.Merge(m, src)
}
func (m *FreezeBalanceContract) XXX_Size() int {
	return xxx_messageInfo_FreezeBalanceContract.Size(m)
}
func (m *FreezeBalanceContract) XXX_DiscardUnknown() {
	xxx_messageInfo_FreezeBalanceContract.DiscardUnknown(m)
}

var xxx_messageInfo_FreezeBalanceContract proto.InternalMessageInfo

func (m *FreezeBalanceContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *FreezeBalanceContract) GetFrozenBalance() int64 {
	if m != nil {
		return m.FrozenBalance
	}
	return 0
}

func (m *FreezeBalanceContract) GetFrozenDuration() int64 {
	if m != nil {
		return m.FrozenDuration
	}
	return 0
}

func (m *FreezeBalanceContract) GetResource() ResourceCode {
	if m != nil {
		return m.Resource
	}
	return ResourceCode_BANDWIDTH
}

type UnfreezeBalanceContract struct {
	OwnerAddress         []byte       `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Resource             ResourceCode `protobuf:"varint,10,opt,name=resource,proto3,enum=protocol.ResourceCode" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UnfreezeBalanceContract) Reset()         { *m = UnfreezeBalanceContract{} }
func (m *UnfreezeBalanceContract) String() string { return proto.CompactTextString(m) }
func (*UnfreezeBalanceContract) ProtoMessage()    {}
func (*UnfreezeBalanceContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{13}
}

func (m *UnfreezeBalanceContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfreezeBalanceContract.Unmarshal(m, b)
}
func (m *UnfreezeBalanceContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfreezeBalanceContract.Marshal(b, m, deterministic)
}
func (m *UnfreezeBalanceContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfreezeBalanceContract.Merge(m, src)
}
func (m *UnfreezeBalanceContract) XXX_Size() int {
	return xxx_messageInfo_UnfreezeBalanceContract.Size(m)
}
func (m *UnfreezeBalanceContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfreezeBalanceContract.DiscardUnknown(m)
}

var xxx_messageInfo_UnfreezeBalanceContract proto.InternalMessageInfo

func (m *UnfreezeBalanceContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *UnfreezeBalanceContract) GetResource() ResourceCode {
	if m != nil {
		return m.Resource
	}
	return ResourceCode_BANDWIDTH
}

type UnfreezeAssetContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfreezeAssetContract) Reset()         { *m = UnfreezeAssetContract{} }
func (m *UnfreezeAssetContract) String() string { return proto.CompactTextString(m) }
func (*UnfreezeAssetContract) ProtoMessage()    {}
func (*UnfreezeAssetContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{14}
}

func (m *UnfreezeAssetContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfreezeAssetContract.Unmarshal(m, b)
}
func (m *UnfreezeAssetContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfreezeAssetContract.Marshal(b, m, deterministic)
}
func (m *UnfreezeAssetContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfreezeAssetContract.Merge(m, src)
}
func (m *UnfreezeAssetContract) XXX_Size() int {
	return xxx_messageInfo_UnfreezeAssetContract.Size(m)
}
func (m *UnfreezeAssetContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfreezeAssetContract.DiscardUnknown(m)
}

var xxx_messageInfo_UnfreezeAssetContract proto.InternalMessageInfo

func (m *UnfreezeAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

type WithdrawBalanceContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawBalanceContract) Reset()         { *m = WithdrawBalanceContract{} }
func (m *WithdrawBalanceContract) String() string { return proto.CompactTextString(m) }
func (*WithdrawBalanceContract) ProtoMessage()    {}
func (*WithdrawBalanceContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{15}
}

func (m *WithdrawBalanceContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawBalanceContract.Unmarshal(m, b)
}
func (m *WithdrawBalanceContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawBalanceContract.Marshal(b, m, deterministic)
}
func (m *WithdrawBalanceContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawBalanceContract.Merge(m, src)
}
func (m *WithdrawBalanceContract) XXX_Size() int {
	return xxx_messageInfo_WithdrawBalanceContract.Size(m)
}
func (m *WithdrawBalanceContract) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawBalanceContract.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawBalanceContract proto.InternalMessageInfo

func (m *WithdrawBalanceContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

type UpdateAssetContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Description          []byte   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url                  []byte   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	NewLimit             int64    `protobuf:"varint,4,opt,name=new_limit,json=newLimit,proto3" json:"new_limit,omitempty"`
	NewPublicLimit       int64    `protobuf:"varint,5,opt,name=new_public_limit,json=newPublicLimit,proto3" json:"new_public_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAssetContract) Reset()         { *m = UpdateAssetContract{} }
func (m *UpdateAssetContract) String() string { return proto.CompactTextString(m) }
func (*UpdateAssetContract) ProtoMessage()    {}
func (*UpdateAssetContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{16}
}

func (m *UpdateAssetContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAssetContract.Unmarshal(m, b)
}
func (m *UpdateAssetContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAssetContract.Marshal(b, m, deterministic)
}
func (m *UpdateAssetContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAssetContract.Merge(m, src)
}
func (m *UpdateAssetContract) XXX_Size() int {
	return xxx_messageInfo_UpdateAssetContract.Size(m)
}
func (m *UpdateAssetContract) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAssetContract.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAssetContract proto.InternalMessageInfo

func (m *UpdateAssetContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *UpdateAssetContract) GetDescription() []byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *UpdateAssetContract) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *UpdateAssetContract) GetNewLimit() int64 {
	if m != nil {
		return m.NewLimit
	}
	return 0
}

func (m *UpdateAssetContract) GetNewPublicLimit() int64 {
	if m != nil {
		return m.NewPublicLimit
	}
	return 0
}

type ProposalCreateContract struct {
	OwnerAddress         []byte          `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Parameters           map[int64]int64 `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProposalCreateContract) Reset()         { *m = ProposalCreateContract{} }
func (m *ProposalCreateContract) String() string { return proto.CompactTextString(m) }
func (*ProposalCreateContract) ProtoMessage()    {}
func (*ProposalCreateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{17}
}

func (m *ProposalCreateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalCreateContract.Unmarshal(m, b)
}
func (m *ProposalCreateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalCreateContract.Marshal(b, m, deterministic)
}
func (m *ProposalCreateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalCreateContract.Merge(m, src)
}
func (m *ProposalCreateContract) XXX_Size() int {
	return xxx_messageInfo_ProposalCreateContract.Size(m)
}
func (m *ProposalCreateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalCreateContract.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalCreateContract proto.InternalMessageInfo

func (m *ProposalCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ProposalCreateContract) GetParameters() map[int64]int64 {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ProposalApproveContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ProposalId           int64    `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	IsAddApproval        bool     `protobuf:"varint,3,opt,name=is_add_approval,json=isAddApproval,proto3" json:"is_add_approval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposalApproveContract) Reset()         { *m = ProposalApproveContract{} }
func (m *ProposalApproveContract) String() string { return proto.CompactTextString(m) }
func (*ProposalApproveContract) ProtoMessage()    {}
func (*ProposalApproveContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{18}
}

func (m *ProposalApproveContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalApproveContract.Unmarshal(m, b)
}
func (m *ProposalApproveContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalApproveContract.Marshal(b, m, deterministic)
}
func (m *ProposalApproveContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalApproveContract.Merge(m, src)
}
func (m *ProposalApproveContract) XXX_Size() int {
	return xxx_messageInfo_ProposalApproveContract.Size(m)
}
func (m *ProposalApproveContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalApproveContract.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalApproveContract proto.InternalMessageInfo

func (m *ProposalApproveContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ProposalApproveContract) GetProposalId() int64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *ProposalApproveContract) GetIsAddApproval() bool {
	if m != nil {
		return m.IsAddApproval
	}
	return false
}

type ProposalDeleteContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ProposalId           int64    `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposalDeleteContract) Reset()         { *m = ProposalDeleteContract{} }
func (m *ProposalDeleteContract) String() string { return proto.CompactTextString(m) }
func (*ProposalDeleteContract) ProtoMessage()    {}
func (*ProposalDeleteContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{19}
}

func (m *ProposalDeleteContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalDeleteContract.Unmarshal(m, b)
}
func (m *ProposalDeleteContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalDeleteContract.Marshal(b, m, deterministic)
}
func (m *ProposalDeleteContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalDeleteContract.Merge(m, src)
}
func (m *ProposalDeleteContract) XXX_Size() int {
	return xxx_messageInfo_ProposalDeleteContract.Size(m)
}
func (m *ProposalDeleteContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalDeleteContract.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalDeleteContract proto.InternalMessageInfo

func (m *ProposalDeleteContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ProposalDeleteContract) GetProposalId() int64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

type CreateSmartContract struct {
	OwnerAddress         []byte         `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	NewContract          *SmartContract `protobuf:"bytes,2,opt,name=new_contract,json=newContract,proto3" json:"new_contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateSmartContract) Reset()         { *m = CreateSmartContract{} }
func (m *CreateSmartContract) String() string { return proto.CompactTextString(m) }
func (*CreateSmartContract) ProtoMessage()    {}
func (*CreateSmartContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{20}
}

func (m *CreateSmartContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSmartContract.Unmarshal(m, b)
}
func (m *CreateSmartContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSmartContract.Marshal(b, m, deterministic)
}
func (m *CreateSmartContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSmartContract.Merge(m, src)
}
func (m *CreateSmartContract) XXX_Size() int {
	return xxx_messageInfo_CreateSmartContract.Size(m)
}
func (m *CreateSmartContract) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSmartContract.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSmartContract proto.InternalMessageInfo

func (m *CreateSmartContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *CreateSmartContract) GetNewContract() *SmartContract {
	if m != nil {
		return m.NewContract
	}
	return nil
}

type TriggerSmartContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress      []byte   `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	CallValue            int64    `protobuf:"varint,3,opt,name=call_value,json=callValue,proto3" json:"call_value,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerSmartContract) Reset()         { *m = TriggerSmartContract{} }
func (m *TriggerSmartContract) String() string { return proto.CompactTextString(m) }
func (*TriggerSmartContract) ProtoMessage()    {}
func (*TriggerSmartContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{21}
}

func (m *TriggerSmartContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerSmartContract.Unmarshal(m, b)
}
func (m *TriggerSmartContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerSmartContract.Marshal(b, m, deterministic)
}
func (m *TriggerSmartContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerSmartContract.Merge(m, src)
}
func (m *TriggerSmartContract) XXX_Size() int {
	return xxx_messageInfo_TriggerSmartContract.Size(m)
}
func (m *TriggerSmartContract) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerSmartContract.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerSmartContract proto.InternalMessageInfo

func (m *TriggerSmartContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *TriggerSmartContract) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *TriggerSmartContract) GetCallValue() int64 {
	if m != nil {
		return m.CallValue
	}
	return 0
}

func (m *TriggerSmartContract) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BuyStorageContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Quant                int64    `protobuf:"varint,2,opt,name=quant,proto3" json:"quant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStorageContract) Reset()         { *m = BuyStorageContract{} }
func (m *BuyStorageContract) String() string { return proto.CompactTextString(m) }
func (*BuyStorageContract) ProtoMessage()    {}
func (*BuyStorageContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{22}
}

func (m *BuyStorageContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStorageContract.Unmarshal(m, b)
}
func (m *BuyStorageContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStorageContract.Marshal(b, m, deterministic)
}
func (m *BuyStorageContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStorageContract.Merge(m, src)
}
func (m *BuyStorageContract) XXX_Size() int {
	return xxx_messageInfo_BuyStorageContract.Size(m)
}
func (m *BuyStorageContract) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStorageContract.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStorageContract proto.InternalMessageInfo

func (m *BuyStorageContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *BuyStorageContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

type BuyStorageBytesContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Bytes                int64    `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStorageBytesContract) Reset()         { *m = BuyStorageBytesContract{} }
func (m *BuyStorageBytesContract) String() string { return proto.CompactTextString(m) }
func (*BuyStorageBytesContract) ProtoMessage()    {}
func (*BuyStorageBytesContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{23}
}

func (m *BuyStorageBytesContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStorageBytesContract.Unmarshal(m, b)
}
func (m *BuyStorageBytesContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStorageBytesContract.Marshal(b, m, deterministic)
}
func (m *BuyStorageBytesContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStorageBytesContract.Merge(m, src)
}
func (m *BuyStorageBytesContract) XXX_Size() int {
	return xxx_messageInfo_BuyStorageBytesContract.Size(m)
}
func (m *BuyStorageBytesContract) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStorageBytesContract.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStorageBytesContract proto.InternalMessageInfo

func (m *BuyStorageBytesContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *BuyStorageBytesContract) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

type SellStorageContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	StorageBytes         int64    `protobuf:"varint,2,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellStorageContract) Reset()         { *m = SellStorageContract{} }
func (m *SellStorageContract) String() string { return proto.CompactTextString(m) }
func (*SellStorageContract) ProtoMessage()    {}
func (*SellStorageContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{24}
}

func (m *SellStorageContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellStorageContract.Unmarshal(m, b)
}
func (m *SellStorageContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellStorageContract.Marshal(b, m, deterministic)
}
func (m *SellStorageContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellStorageContract.Merge(m, src)
}
func (m *SellStorageContract) XXX_Size() int {
	return xxx_messageInfo_SellStorageContract.Size(m)
}
func (m *SellStorageContract) XXX_DiscardUnknown() {
	xxx_messageInfo_SellStorageContract.DiscardUnknown(m)
}

var xxx_messageInfo_SellStorageContract proto.InternalMessageInfo

func (m *SellStorageContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *SellStorageContract) GetStorageBytes() int64 {
	if m != nil {
		return m.StorageBytes
	}
	return 0
}

type ExchangeCreateContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	FirstTokenId         []byte   `protobuf:"bytes,2,opt,name=first_token_id,json=firstTokenId,proto3" json:"first_token_id,omitempty"`
	FirstTokenBalance    int64    `protobuf:"varint,3,opt,name=first_token_balance,json=firstTokenBalance,proto3" json:"first_token_balance,omitempty"`
	SecondTokenId        []byte   `protobuf:"bytes,4,opt,name=second_token_id,json=secondTokenId,proto3" json:"second_token_id,omitempty"`
	SecondTokenBalance   int64    `protobuf:"varint,5,opt,name=second_token_balance,json=secondTokenBalance,proto3" json:"second_token_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeCreateContract) Reset()         { *m = ExchangeCreateContract{} }
func (m *ExchangeCreateContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeCreateContract) ProtoMessage()    {}
func (*ExchangeCreateContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{25}
}

func (m *ExchangeCreateContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeCreateContract.Unmarshal(m, b)
}
func (m *ExchangeCreateContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeCreateContract.Marshal(b, m, deterministic)
}
func (m *ExchangeCreateContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeCreateContract.Merge(m, src)
}
func (m *ExchangeCreateContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeCreateContract.Size(m)
}
func (m *ExchangeCreateContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeCreateContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeCreateContract proto.InternalMessageInfo

func (m *ExchangeCreateContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeCreateContract) GetFirstTokenId() []byte {
	if m != nil {
		return m.FirstTokenId
	}
	return nil
}

func (m *ExchangeCreateContract) GetFirstTokenBalance() int64 {
	if m != nil {
		return m.FirstTokenBalance
	}
	return 0
}

func (m *ExchangeCreateContract) GetSecondTokenId() []byte {
	if m != nil {
		return m.SecondTokenId
	}
	return nil
}

func (m *ExchangeCreateContract) GetSecondTokenBalance() int64 {
	if m != nil {
		return m.SecondTokenBalance
	}
	return 0
}

type ExchangeInjectContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	TokenId              []byte   `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Quant                int64    `protobuf:"varint,4,opt,name=quant,proto3" json:"quant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeInjectContract) Reset()         { *m = ExchangeInjectContract{} }
func (m *ExchangeInjectContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeInjectContract) ProtoMessage()    {}
func (*ExchangeInjectContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{26}
}

func (m *ExchangeInjectContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeInjectContract.Unmarshal(m, b)
}
func (m *ExchangeInjectContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeInjectContract.Marshal(b, m, deterministic)
}
func (m *ExchangeInjectContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeInjectContract.Merge(m, src)
}
func (m *ExchangeInjectContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeInjectContract.Size(m)
}
func (m *ExchangeInjectContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeInjectContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeInjectContract proto.InternalMessageInfo

func (m *ExchangeInjectContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeInjectContract) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *ExchangeInjectContract) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *ExchangeInjectContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

type ExchangeWithdrawContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	TokenId              []byte   `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Quant                int64    `protobuf:"varint,4,opt,name=quant,proto3" json:"quant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeWithdrawContract) Reset()         { *m = ExchangeWithdrawContract{} }
func (m *ExchangeWithdrawContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeWithdrawContract) ProtoMessage()    {}
func (*ExchangeWithdrawContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{27}
}

func (m *ExchangeWithdrawContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeWithdrawContract.Unmarshal(m, b)
}
func (m *ExchangeWithdrawContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeWithdrawContract.Marshal(b, m, deterministic)
}
func (m *ExchangeWithdrawContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeWithdrawContract.Merge(m, src)
}
func (m *ExchangeWithdrawContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeWithdrawContract.Size(m)
}
func (m *ExchangeWithdrawContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeWithdrawContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeWithdrawContract proto.InternalMessageInfo

func (m *ExchangeWithdrawContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeWithdrawContract) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *ExchangeWithdrawContract) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *ExchangeWithdrawContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

type ExchangeTransactionContract struct {
	OwnerAddress         []byte   `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ExchangeId           int64    `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	TokenId              []byte   `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Quant                int64    `protobuf:"varint,4,opt,name=quant,proto3" json:"quant,omitempty"`
	Expected             int64    `protobuf:"varint,5,opt,name=expected,proto3" json:"expected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeTransactionContract) Reset()         { *m = ExchangeTransactionContract{} }
func (m *ExchangeTransactionContract) String() string { return proto.CompactTextString(m) }
func (*ExchangeTransactionContract) ProtoMessage()    {}
func (*ExchangeTransactionContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c87e605bbc8c70b, []int{28}
}

func (m *ExchangeTransactionContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeTransactionContract.Unmarshal(m, b)
}
func (m *ExchangeTransactionContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeTransactionContract.Marshal(b, m, deterministic)
}
func (m *ExchangeTransactionContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeTransactionContract.Merge(m, src)
}
func (m *ExchangeTransactionContract) XXX_Size() int {
	return xxx_messageInfo_ExchangeTransactionContract.Size(m)
}
func (m *ExchangeTransactionContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeTransactionContract.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeTransactionContract proto.InternalMessageInfo

func (m *ExchangeTransactionContract) GetOwnerAddress() []byte {
	if m != nil {
		return m.OwnerAddress
	}
	return nil
}

func (m *ExchangeTransactionContract) GetExchangeId() int64 {
	if m != nil {
		return m.ExchangeId
	}
	return 0
}

func (m *ExchangeTransactionContract) GetTokenId() []byte {
	if m != nil {
		return m.TokenId
	}
	return nil
}

func (m *ExchangeTransactionContract) GetQuant() int64 {
	if m != nil {
		return m.Quant
	}
	return 0
}

func (m *ExchangeTransactionContract) GetExpected() int64 {
	if m != nil {
		return m.Expected
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.ResourceCode", ResourceCode_name, ResourceCode_value)
	proto.RegisterType((*AccountCreateContract)(nil), "protocol.AccountCreateContract")
	proto.RegisterType((*AccountUpdateContract)(nil), "protocol.AccountUpdateContract")
	proto.RegisterType((*SetAccountIdContract)(nil), "protocol.SetAccountIdContract")
	proto.RegisterType((*TransferContract)(nil), "protocol.TransferContract")
	proto.RegisterType((*TransferAssetContract)(nil), "protocol.TransferAssetContract")
	proto.RegisterType((*VoteAssetContract)(nil), "protocol.VoteAssetContract")
	proto.RegisterType((*VoteWitnessContract)(nil), "protocol.VoteWitnessContract")
	proto.RegisterType((*VoteWitnessContract_Vote)(nil), "protocol.VoteWitnessContract.Vote")
	proto.RegisterType((*UpdateSettingContract)(nil), "protocol.UpdateSettingContract")
	proto.RegisterType((*WitnessCreateContract)(nil), "protocol.WitnessCreateContract")
	proto.RegisterType((*WitnessUpdateContract)(nil), "protocol.WitnessUpdateContract")
	proto.RegisterType((*AssetIssueContract)(nil), "protocol.AssetIssueContract")
	proto.RegisterType((*AssetIssueContract_FrozenSupply)(nil), "protocol.AssetIssueContract.FrozenSupply")
	proto.RegisterType((*ParticipateAssetIssueContract)(nil), "protocol.ParticipateAssetIssueContract")
	proto.RegisterType((*FreezeBalanceContract)(nil), "protocol.FreezeBalanceContract")
	proto.RegisterType((*UnfreezeBalanceContract)(nil), "protocol.UnfreezeBalanceContract")
	proto.RegisterType((*UnfreezeAssetContract)(nil), "protocol.UnfreezeAssetContract")
	proto.RegisterType((*WithdrawBalanceContract)(nil), "protocol.WithdrawBalanceContract")
	proto.RegisterType((*UpdateAssetContract)(nil), "protocol.UpdateAssetContract")
	proto.RegisterType((*ProposalCreateContract)(nil), "protocol.ProposalCreateContract")
	proto.RegisterMapType((map[int64]int64)(nil), "protocol.ProposalCreateContract.ParametersEntry")
	proto.RegisterType((*ProposalApproveContract)(nil), "protocol.ProposalApproveContract")
	proto.RegisterType((*ProposalDeleteContract)(nil), "protocol.ProposalDeleteContract")
	proto.RegisterType((*CreateSmartContract)(nil), "protocol.CreateSmartContract")
	proto.RegisterType((*TriggerSmartContract)(nil), "protocol.TriggerSmartContract")
	proto.RegisterType((*BuyStorageContract)(nil), "protocol.BuyStorageContract")
	proto.RegisterType((*BuyStorageBytesContract)(nil), "protocol.BuyStorageBytesContract")
	proto.RegisterType((*SellStorageContract)(nil), "protocol.SellStorageContract")
	proto.RegisterType((*ExchangeCreateContract)(nil), "protocol.ExchangeCreateContract")
	proto.RegisterType((*ExchangeInjectContract)(nil), "protocol.ExchangeInjectContract")
	proto.RegisterType((*ExchangeWithdrawContract)(nil), "protocol.ExchangeWithdrawContract")
	proto.RegisterType((*ExchangeTransactionContract)(nil), "protocol.ExchangeTransactionContract")
}

func init() { proto.RegisterFile("core/Contract.proto", fileDescriptor_8c87e605bbc8c70b) }

var fileDescriptor_8c87e605bbc8c70b = []byte{
	// 1485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0xbe, 0xb4, 0x2c, 0x5b, 0x3a, 0x92, 0x7f, 0x42, 0x4b, 0x96, 0xe2, 0xc0, 0x88, 0xc3, 0xdc,
	0x9b, 0x6b, 0x5f, 0xe0, 0xca, 0x81, 0xbb, 0x09, 0x82, 0xb4, 0x80, 0xfc, 0x93, 0xc6, 0x40, 0xa0,
	0x1a, 0xb2, 0x9c, 0xa0, 0x29, 0x50, 0x62, 0x4c, 0x1e, 0x2b, 0x6c, 0x28, 0x92, 0x9d, 0x19, 0xda,
	0x56, 0x5e, 0xa0, 0x8b, 0x2e, 0xfa, 0xb3, 0x6b, 0x1f, 0xa1, 0xab, 0x6e, 0xba, 0xef, 0x13, 0x74,
	0xdd, 0x7d, 0xd7, 0x7d, 0x87, 0x62, 0xfe, 0x68, 0x5a, 0x8e, 0x51, 0x4b, 0x28, 0x90, 0x95, 0x39,
	0xdf, 0x9c, 0xf3, 0xcd, 0x37, 0x67, 0xce, 0x39, 0x33, 0x16, 0x2c, 0x79, 0x31, 0xc5, 0xcd, 0x9d,
	0x38, 0xe2, 0x94, 0x78, 0xbc, 0x95, 0xd0, 0x98, 0xc7, 0x76, 0x49, 0xfe, 0xf1, 0xe2, 0x70, 0x65,
	0x41, 0x4e, 0xf7, 0x68, 0x1c, 0xa9, 0x29, 0xe7, 0x5b, 0x0b, 0xea, 0x6d, 0xcf, 0x8b, 0xd3, 0x88,
	0xef, 0x50, 0x24, 0x1c, 0x8d, 0xab, 0x7d, 0x1f, 0xe6, 0xe2, 0xb3, 0x08, 0xa9, 0x4b, 0x7c, 0x9f,
	0x22, 0x63, 0x4d, 0x6b, 0xcd, 0x5a, 0xaf, 0x76, 0xab, 0x12, 0x6c, 0x2b, 0xcc, 0xfe, 0x2f, 0x2c,
	0x10, 0xe5, 0x9d, 0x99, 0x4d, 0x49, 0xb3, 0x79, 0x0d, 0x1b, 0xc3, 0x0d, 0x98, 0xe6, 0xc3, 0x04,
	0x9b, 0x85, 0x35, 0x6b, 0x7d, 0x7e, 0xab, 0xde, 0x32, 0x8a, 0x5a, 0x7a, 0xf1, 0xde, 0x30, 0xc1,
	0xae, 0x34, 0x71, 0xdc, 0x4c, 0xd1, 0x51, 0xe2, 0xe7, 0x15, 0xdd, 0x83, 0xaa, 0x59, 0x2c, 0x22,
	0x03, 0xd4, 0x82, 0x2a, 0x1a, 0xeb, 0x90, 0x01, 0x5e, 0x15, 0x3d, 0x75, 0x55, 0xb4, 0xf3, 0x0a,
	0x6a, 0x87, 0xc8, 0xf5, 0x1a, 0xfb, 0x7e, 0xc6, 0xbf, 0x0a, 0x60, 0xf8, 0x03, 0x5f, 0xb3, 0x97,
	0x89, 0x31, 0xbb, 0x19, 0x77, 0x04, 0x8b, 0x3d, 0x4a, 0x22, 0x76, 0x82, 0x74, 0xbc, 0x48, 0xae,
	0x02, 0xf0, 0x78, 0x84, 0xba, 0xcc, 0x63, 0x33, 0xbd, 0x0c, 0x33, 0x64, 0x20, 0x84, 0xc8, 0x08,
	0x16, 0xba, 0x7a, 0xe4, 0x7c, 0x6f, 0x41, 0xdd, 0x2c, 0xd8, 0x66, 0x0c, 0xf9, 0xa5, 0xdd, 0x08,
	0x20, 0x1f, 0xab, 0xb2, 0x44, 0x6e, 0x1c, 0xa9, 0x11, 0x51, 0x85, 0xeb, 0x45, 0x4d, 0x5f, 0x12,
	0xf5, 0xb5, 0x05, 0xb7, 0x5e, 0xc4, 0x1c, 0x2f, 0x0b, 0xba, 0x51, 0x18, 0xee, 0x41, 0xf5, 0x34,
	0xe6, 0x98, 0x53, 0x55, 0x10, 0x67, 0x2c, 0x30, 0x63, 0xd2, 0x84, 0x59, 0x96, 0x26, 0x49, 0x4c,
	0x55, 0x2c, 0x4a, 0x5d, 0x33, 0xb4, 0x6b, 0x50, 0x94, 0x87, 0xd5, 0x2c, 0xae, 0x59, 0xeb, 0xc5,
	0xae, 0x1a, 0x38, 0xbf, 0x5b, 0xb0, 0x24, 0xd4, 0xbc, 0x0c, 0x78, 0x84, 0x8c, 0x8d, 0xa7, 0xe7,
	0x11, 0x14, 0xc5, 0xda, 0x4a, 0x48, 0x65, 0xcb, 0xb9, 0x48, 0xdc, 0x77, 0x50, 0x4a, 0xac, 0xab,
	0x1c, 0xae, 0x97, 0xb9, 0xf2, 0x0c, 0xa6, 0x85, 0xe1, 0x95, 0xbd, 0xea, 0x7c, 0xce, 0xef, 0x75,
	0x15, 0x40, 0x9a, 0xa8, 0x6d, 0x4d, 0xc9, 0x28, 0x97, 0x05, 0xb2, 0x23, 0xb7, 0xf6, 0x93, 0x05,
	0x75, 0x55, 0x24, 0x87, 0xc8, 0x79, 0x10, 0xf5, 0xc7, 0xdb, 0xdc, 0x06, 0x2c, 0x7a, 0xda, 0x61,
	0x24, 0x0d, 0x16, 0x0c, 0x6e, 0x4c, 0xdb, 0xb0, 0xea, 0xc5, 0x11, 0x4b, 0x07, 0xe8, 0xa6, 0x0c,
	0xa9, 0x4b, 0x91, 0xc5, 0x29, 0xf5, 0xd0, 0x4d, 0x90, 0x7a, 0x98, 0xa5, 0xe5, 0x8a, 0x36, 0x3a,
	0x62, 0x48, 0xbb, 0xda, 0xe4, 0x40, 0x59, 0x38, 0x1d, 0xa8, 0x9b, 0x78, 0x4d, 0xd0, 0x69, 0x16,
	0xa1, 0x90, 0xd2, 0x50, 0xcb, 0x13, 0x9f, 0xce, 0x67, 0x19, 0xdf, 0x48, 0x9f, 0xb8, 0x69, 0xbd,
	0xa5, 0xd2, 0xcd, 0x15, 0xb4, 0x55, 0x95, 0xda, 0x0a, 0x39, 0xa2, 0xa1, 0xf3, 0x47, 0x11, 0x6c,
	0x99, 0xbe, 0xfb, 0x8c, 0xa5, 0x63, 0x52, 0xdb, 0x30, 0x2d, 0x6b, 0x4e, 0x69, 0x95, 0xdf, 0x02,
	0x23, 0xc7, 0xc7, 0x54, 0xd7, 0x90, 0xfc, 0x16, 0xe7, 0xcf, 0x63, 0x4e, 0x42, 0x57, 0x24, 0x46,
	0x38, 0xd4, 0x45, 0x54, 0x91, 0xd8, 0xa1, 0x84, 0xec, 0x0e, 0xcc, 0x9d, 0xd0, 0xf8, 0x2d, 0x46,
	0xc6, 0xa6, 0x28, 0xd3, 0x70, 0x23, 0xd7, 0x3f, 0xaf, 0x88, 0x6c, 0x3d, 0x95, 0x1e, 0x8a, 0xa1,
	0x5b, 0x3d, 0xc9, 0x8d, 0xec, 0x06, 0xcc, 0x72, 0x7a, 0xee, 0x46, 0xe9, 0xa0, 0x39, 0x23, 0x6b,
	0x64, 0x86, 0xd3, 0xf3, 0x4e, 0x3a, 0x10, 0xe1, 0x15, 0x60, 0x49, 0x82, 0xe2, 0x53, 0x04, 0x88,
	0x71, 0x42, 0xb9, 0xcb, 0x83, 0x01, 0x36, 0xcb, 0x2a, 0xf5, 0x24, 0xd2, 0x0b, 0x06, 0x68, 0xdf,
	0x86, 0x12, 0x46, 0xbe, 0x9a, 0x04, 0x39, 0x39, 0x8b, 0x91, 0x2f, 0xa7, 0x6a, 0x50, 0x8c, 0xa9,
	0x8f, 0xb4, 0x59, 0x91, 0xb8, 0x1a, 0x64, 0xa9, 0xcc, 0xc4, 0x15, 0xd4, 0x5c, 0x94, 0x0b, 0xc9,
	0x54, 0x3e, 0x14, 0x80, 0xbd, 0x06, 0x15, 0x1f, 0x99, 0x47, 0x83, 0x84, 0x07, 0x71, 0xd4, 0xac,
	0xa9, 0x5a, 0xc8, 0x41, 0x26, 0x03, 0xea, 0x59, 0x06, 0xd8, 0x9b, 0x50, 0x3b, 0xa1, 0x88, 0xae,
	0xee, 0x73, 0xc8, 0xdd, 0x30, 0x18, 0x04, 0xbc, 0xb9, 0x2c, 0xd7, 0xbd, 0x25, 0xe6, 0x64, 0x78,
	0x3a, 0xc8, 0x9f, 0x8b, 0x09, 0xfb, 0x09, 0xdc, 0x49, 0xd2, 0xe3, 0x30, 0xf0, 0xdc, 0x77, 0xfa,
	0x35, 0xa4, 0x5f, 0x43, 0x99, 0x3c, 0xbd, 0xb9, 0x77, 0xca, 0x48, 0x1f, 0x9b, 0xcd, 0xeb, 0xbc,
	0x8f, 0xc4, 0x74, 0xce, 0x3b, 0x24, 0x1c, 0x19, 0x57, 0x24, 0xc2, 0x5d, 0xc6, 0xf0, 0x76, 0xde,
	0xfb, 0xb9, 0xb4, 0x10, 0x1c, 0x1d, 0x94, 0xe1, 0x5e, 0xe9, 0x41, 0x35, 0x7f, 0xac, 0x22, 0x11,
	0x75, 0x62, 0xe8, 0x0e, 0x6c, 0x49, 0x7f, 0x7d, 0xda, 0x6d, 0x89, 0xd9, 0x77, 0xa1, 0xa2, 0x8d,
	0x7c, 0x32, 0x64, 0xba, 0x7d, 0x80, 0x82, 0x76, 0xc9, 0x90, 0x39, 0x3f, 0x5a, 0xb0, 0x7a, 0x40,
	0x28, 0x0f, 0xbc, 0x20, 0x21, 0xba, 0x5f, 0x4f, 0x90, 0xf0, 0x7f, 0x73, 0x77, 0x5d, 0xbe, 0x89,
	0x0a, 0xa3, 0x37, 0xd1, 0x75, 0xb7, 0xc8, 0xaf, 0x16, 0xd4, 0x45, 0x08, 0xde, 0xe2, 0x36, 0x09,
	0x49, 0xe4, 0x8d, 0x29, 0xea, 0x3f, 0x30, 0xaf, 0x37, 0x7f, 0xac, 0xdc, 0xf5, 0xfe, 0x75, 0xdc,
	0x34, 0xa7, 0x78, 0xc1, 0x98, 0x18, 0xa5, 0x94, 0xc8, 0xdc, 0x53, 0xad, 0x4c, 0x7b, 0xef, 0x6a,
	0xd4, 0xde, 0x82, 0x92, 0x69, 0x7a, 0x32, 0xe1, 0xe7, 0xb7, 0x96, 0x2f, 0xaa, 0xd0, 0xf4, 0xba,
	0x9d, 0xd8, 0xc7, 0x6e, 0x66, 0xe7, 0x50, 0x68, 0x1c, 0x45, 0x27, 0x93, 0xef, 0x61, 0x92, 0x35,
	0x9f, 0x40, 0xdd, 0xac, 0x39, 0xfe, 0xfd, 0xeb, 0x7c, 0x04, 0x8d, 0x97, 0x01, 0x7f, 0xed, 0x53,
	0x72, 0x36, 0x89, 0x62, 0xe7, 0x17, 0x0b, 0x96, 0x54, 0x3b, 0x9e, 0xe0, 0xf2, 0x1f, 0xe9, 0x01,
	0x53, 0xd7, 0xf6, 0x80, 0xc2, 0x45, 0x0f, 0xb8, 0x03, 0xe5, 0x08, 0xcf, 0x74, 0x01, 0xab, 0x04,
	0x2a, 0x45, 0x78, 0xa6, 0x2a, 0x76, 0x1d, 0x16, 0xc5, 0xa4, 0xa9, 0x3b, 0x69, 0x53, 0x54, 0xa7,
	0x1b, 0xe1, 0xd9, 0x81, 0xaa, 0x35, 0x81, 0x3a, 0xbf, 0x59, 0xb0, 0x7c, 0x40, 0xe3, 0x24, 0x66,
	0x24, 0x9c, 0xe4, 0x7a, 0x3a, 0x00, 0x48, 0x08, 0x25, 0x03, 0xe4, 0x48, 0xcd, 0x63, 0xe1, 0xe1,
	0xc5, 0x59, 0xbd, 0x9b, 0xba, 0x75, 0x90, 0xb9, 0xec, 0x45, 0x9c, 0x0e, 0xbb, 0x39, 0x8e, 0x95,
	0x0f, 0x61, 0x61, 0x64, 0x5a, 0xec, 0xfe, 0x0d, 0x0e, 0x75, 0xa9, 0x8b, 0x4f, 0xd1, 0x6a, 0x4f,
	0x49, 0x98, 0x9a, 0xdc, 0x56, 0x83, 0xc7, 0x53, 0x8f, 0x2c, 0xe7, 0x2b, 0x0b, 0x1a, 0x66, 0xd5,
	0x76, 0x92, 0xd0, 0xf8, 0x74, 0xcc, 0x1d, 0xdd, 0x85, 0x4a, 0xa2, 0xfd, 0xc5, 0x73, 0x58, 0x37,
	0x0f, 0x03, 0xed, 0xfb, 0xf6, 0x03, 0x58, 0x08, 0x98, 0xa0, 0x70, 0x89, 0xe4, 0x27, 0xa1, 0x7e,
	0xe8, 0xcc, 0x05, 0xac, 0xed, 0xfb, 0x6d, 0x0d, 0x3a, 0x9f, 0x5f, 0x44, 0x76, 0x17, 0x43, 0xe4,
	0xff, 0xb0, 0x0e, 0xe7, 0x14, 0x96, 0x54, 0x58, 0x0f, 0x07, 0x84, 0x8e, 0x99, 0x71, 0x8f, 0xa1,
	0x2a, 0x12, 0xc4, 0xbc, 0x76, 0x24, 0x7b, 0x65, 0xab, 0x71, 0x71, 0x70, 0x97, 0x38, 0xbb, 0x95,
	0x08, 0xcf, 0xcc, 0xc0, 0xf9, 0xc1, 0x82, 0x5a, 0x8f, 0x06, 0xfd, 0x3e, 0xd2, 0x09, 0x56, 0x1e,
	0xe3, 0xed, 0xb5, 0x0a, 0xe0, 0x91, 0x30, 0x74, 0xd5, 0x49, 0xab, 0xee, 0x54, 0x16, 0xc8, 0x0b,
	0x01, 0x88, 0xa7, 0x85, 0x4f, 0x38, 0x91, 0xc9, 0x5f, 0xed, 0xca, 0x6f, 0xe7, 0x13, 0xb0, 0xb7,
	0xd3, 0xe1, 0x21, 0x8f, 0x29, 0xe9, 0x8f, 0x19, 0xef, 0x1a, 0x14, 0xbf, 0x4c, 0x49, 0xf6, 0xda,
	0x54, 0x03, 0xa7, 0x07, 0x8d, 0x0b, 0xc2, 0xed, 0x21, 0x47, 0x36, 0x36, 0xeb, 0xf1, 0x50, 0xbd,
	0xa3, 0x25, 0xab, 0x1c, 0x38, 0x2e, 0x2c, 0x1d, 0x62, 0x18, 0x4e, 0xa4, 0xf3, 0x3e, 0xcc, 0x31,
	0xe5, 0xe7, 0xe6, 0x99, 0xab, 0x2c, 0xa7, 0xd1, 0xf9, 0xd3, 0x82, 0xe5, 0xbd, 0x73, 0xef, 0x35,
	0x89, 0xfa, 0x38, 0x49, 0x59, 0xff, 0x1b, 0xe6, 0x4f, 0x02, 0xca, 0xb8, 0xcb, 0xe3, 0x37, 0x18,
	0x99, 0xfc, 0xab, 0x76, 0xab, 0x12, 0xed, 0x09, 0x70, 0xdf, 0xb7, 0x5b, 0xb0, 0x94, 0xb7, 0x32,
	0xf7, 0x4d, 0x41, 0x3f, 0x43, 0x32, 0x53, 0x73, 0xe7, 0x3c, 0x80, 0x05, 0x86, 0x5e, 0x2c, 0x9e,
	0x4f, 0x86, 0x56, 0x1d, 0xde, 0x9c, 0x82, 0x0d, 0xef, 0x43, 0xa8, 0x5d, 0xb2, 0x33, 0xc4, 0xaa,
	0x85, 0xd9, 0x39, 0x63, 0xcd, 0xec, 0x7c, 0x93, 0xdb, 0xef, 0x7e, 0xf4, 0x05, 0x7a, 0x7c, 0xec,
	0x62, 0x43, 0xed, 0x9e, 0x2b, 0x36, 0x03, 0xed, 0xfb, 0xe2, 0xd9, 0x97, 0x69, 0x56, 0x5d, 0x78,
	0x96, 0x6b, 0xb5, 0x59, 0xe2, 0x4c, 0xe7, 0x13, 0xe7, 0x3b, 0x0b, 0x9a, 0x46, 0x91, 0xb9, 0x59,
	0xde, 0xb7, 0xa6, 0x9f, 0x2d, 0xb8, 0x63, 0x34, 0xc9, 0x7f, 0x9e, 0x89, 0x27, 0x6e, 0x97, 0xf7,
	0x2c, 0xcb, 0x5e, 0x81, 0x12, 0x9e, 0x27, 0xe8, 0x71, 0xf4, 0xf5, 0x11, 0x67, 0xe3, 0xff, 0x6d,
	0x40, 0x35, 0x7f, 0xdf, 0xdb, 0x73, 0x50, 0xde, 0x6e, 0x77, 0x76, 0x5f, 0xee, 0xef, 0xf6, 0x9e,
	0x2d, 0xfe, 0xcb, 0x06, 0x98, 0xd9, 0xeb, 0xec, 0x75, 0x3f, 0xfe, 0x74, 0xd1, 0xda, 0x7e, 0x0a,
	0x0b, 0x31, 0xed, 0xb7, 0x78, 0xf6, 0x23, 0x0f, 0xdb, 0x2e, 0x99, 0xad, 0xbd, 0xda, 0xe8, 0x07,
	0xfc, 0x75, 0x7a, 0xdc, 0xf2, 0xe2, 0xc1, 0xa6, 0xb0, 0x30, 0x8d, 0x6e, 0xb3, 0x4f, 0x13, 0xef,
	0xff, 0x7d, 0xc2, 0xf1, 0x8c, 0x0c, 0x37, 0xc5, 0x8b, 0xfc, 0x78, 0x46, 0xce, 0x7d, 0xf0, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x45, 0x8d, 0x07, 0x53, 0x12, 0x00, 0x00,
}
